apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: default
data:
  BASE_URL: http://localhost

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE test;
    USE test;
    CREATE TABLE `orders` (
    `order_id` INT unsigned NOT NULL,
    `region` VARCHAR(255) NOT NULL,
    `country` VARCHAR(150) NOT NULL,
    `item_type` VARCHAR(100) NOT NULL,
    `sales_channel` VARCHAR(20) NOT NULL,
    `order_priority` VARCHAR(2) NOT NULL,
    `order_date` DATE NOT NULL,
    `ship_date` DATE NOT NULL,
    `units_sold` INT unsigned NOT NULL,
    `unit_price` FLOAT unsigned NOT NULL,
    `unit_cost` FLOAT unsigned NOT NULL,
    `total_revenue` FLOAT unsigned NOT NULL,
    `total_cost` FLOAT unsigned NOT NULL,
    `total_profit` FLOAT unsigned NOT NULL,
    `nric` VARCHAR(10) NOT NULL,
    PRIMARY KEY (`order_id`));
