apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  CELERY_BROKER_URL: cmVkaXM6Ly9yZWRpcy1zcnY6NjM3OS8wCg==
  CELERY_BACKEND: cmVkaXM6Ly9yZWRpcy1zcnY6NjM3OS8xCg==
  SOCKETIO_REDIS_URL: cmVkaXM6Ly9yZWRpcy1zcnY6NjM3OS8wCg==